# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'MakeItSo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MakeItSo
  pod 'Resolver'
  pod 'Disk', '~> 0.6.4'

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Functions'
  
  # pod 'FirebaseFirestoreSwift'
  pod 'FirebaseFirestoreSwift', :path => '../../../firebase-ios-sdk/pf-combine/firebase-ios-sdk'
end
